### ISSUE TITLE
not working on ubuntu

### ISSUE THREAD

**Issue by x0rzkov** [srohr/gpt2-news-api#3]
Hi,

Hope you are all well !

I have the following error.

```bash
/home/ubuntu/gpt2-news-api# python3 generator.py
Generating text with prompt: ""

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index -1 of dimension 1 out of bounds.
	 [[{{node sample_sequence/strided_slice_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "generator.py", line 96, in <module>
    result = generate(prompt)
  File "generator.py", line 83, in generate
    context: [context_tokens for _ in range(batch_size)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index -1 of dimension 1 out of bounds.
	 [[node sample_sequence/strided_slice_1 (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'sample_sequence/strided_slice_1':
  File "generator.py", line 96, in <module>
    result = generate(prompt)
  File "generator.py", line 72, in generate
    temperature=temperature, top_k=top_k, top_p=top_p
  File "gpt-2/src/sample.py", line 74, in sample_sequence
    past, prev, output = body(None, context, context)
  File "gpt-2/src/sample.py", line 64, in body
    logits = next_outputs['logits'][:, -1, :]  / tf.to_float(temperature)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 802, in _slice_helper
    name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 968, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 10392, in strided_slice
    shrink_axis_mask=shrink_axis_mask, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()
```

Any idea how to solve it ?

Cheers,
X

**Comment by srohr** [comment]
Looks like you didn't give it a prompt, considering the output 

`Generating text with prompt: "" `

Also, a warning, this repo is a personal project which I haven't been keeping up with. It's probably not in a very stable state to be used by others.
